---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    groupBy: ["alertname", "job"]
    groupInterval: 10m
    groupWait: 1m
    receiver: pushover
    repeatInterval: 12h
    routes:
      - receiver: "null"
        matchers: [{ name: alertname, value: InfoInhibitor, matchType: = }]
      - receiver: heartbeat
        groupInterval: 15s
        groupWait: 0s
        repeatInterval: 5m
        matchers: [{ name: alertname, value: Watchdog, matchType: = }]
      - receiver: pushover
        matchers: [{ name: severity, value: critical, matchType: = }]
  inhibitRules:
    - equal: ["alertname", "namespace"]
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =
  receivers:
    - name: "null"
    - name: heartbeat
      webhookConfigs:
        - urlSecret:
            name: &secret alertmanager-secret
            key: ALERTMANAGER_HEARTBEAT_URL
    - name: pushover
      pushoverConfigs:
        - html: true
          message: |-
            {{- range .Alerts }}
              {{- if ne .Annotations.description "" }}
                {{ .Annotations.description | truncate 400 }}
              {{- else if ne .Annotations.summary "" }}
                {{ .Annotations.summary | truncate 400 }}
              {{- else if ne .Annotations.message "" }}
                {{ .Annotations.message | truncate 400 }}
              {{- else }}
                Alert description not available
              {{- end }}
              {{- if .Labels.instance }}<small><b>Instance:</b> {{ .Labels.instance }}</small>{{ end }}
              {{- if .Labels.namespace }}<small><b>Namespace:</b> {{ .Labels.namespace }}</small>{{ end }}
              {{- if .Labels.pod }}<small><b>Pod:</b> {{ .Labels.pod }}</small>{{ end }}
            {{- end }}
          priority: |-
            {{ if eq .Status "firing" }}1{{ else }}0{{ end }}
          sendResolved: true
          sound: gamelan
          title: >-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]
            {{ .CommonLabels.alertname }}
          ttl: 3600s
          token:
            name: *secret
            key: ALERTMANAGER_PUSHOVER_APP_TOKEN
          userKey:
            name: *secret
            key: ALERTMANAGER_PUSHOVER_USER_KEY
          urlTitle: View in Alertmanager
