---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-prometheus-stack-additional
spec:
  groups:
    - name: kube-prometheus-stack-additional.rules
      rules:
        - alert: DockerhubRateLimitRisk
          expr: |
            count(time() - container_last_seen{image=~"(docker.io).*",container!=""} < 30) > 100
          annotations:
            summary: >-
              Kubernetes cluster Dockerhub rate limit risk
          labels:
            severity: critical

        - alert: OomKilled
          expr: |
            (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
          annotations:
            summary: >-
              Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.
            runbook_url: "https://github.com/cpritchett/home-ops/blob/main/docs/CLUSTER-TROUBLESHOOTING.md#memory-issues"
            description: >-
              Container ran out of memory. Check resource limits with `kubectl describe pod {{ $labels.pod }} -n {{ $labels.namespace }}` and consider increasing memory limits or investigate memory leaks.
          labels:
            severity: critical
