---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app recyclarr
  namespace: &namespace media
spec:
  suspend: true # TODO: I may pull this out completely, there are some easier to use alternatives. as it is the config isn't complete and I'll fix it later
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  interval: 1h
  path: ./kubernetes/apps/media/recyclarr/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_SCHEDULE: "35 5/13/21 * * *"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
