[env]
KUBECONFIG = '{{config_root}}/kubernetes/kubeconfig'
MINIJINJA_CONFIG_FILE = '{{config_root}}/.minijinja.toml'
TALOSCONFIG = '{{config_root}}/talos/talosconfig'
TALOS_VERSION = "v1.11.0-beta.2"
KUBERNETES_VERSION = "v1.33.4"
MACHINE_TYPE = "controlplane"

[tools]
helmfile = "1.1.5"
kubectl = "1.34.0"
talosctl = "1.11.0-beta.2"
task = "3.44.1"
#"cargo:minijinja-cli" = "latest"
#"cargo:jinja-lsp" = "latest"
yq = "4.47.1"
rust = "1.89.0"
helm = "3.18.6"
#cargo = "latest"
flux2 = "2.6.4"
"ubi:kubernetes-sigs/krew" = "latest"

# Additional CLI tools (migrated from Brewfile)
jq = "1.8.1"
kustomize = "5.7.1"
"ubi:FiloSottile/age" = "latest"
"ubi:cloudflare/cloudflared" = "latest"
"ubi:cli/cli[exe=gh]" = "latest"
"ubi:derailed/k9s" = "latest"
"ubi:kubecolor/kubecolor" = "latest"
"ubi:yannh/kubeconform" = "latest"
"ubi:stern/stern" = "latest"
"ubi:sachaos/viddy" = "latest"
restic = "0.18.0"

[hooks]
# Check for moreutils after install
"postinstall" = '''
if ! command -v chronic >/dev/null 2>&1; then
  echo ""
  echo "⚠️  NOTICE: moreutils not detected in PATH"
  echo "   Install with: sudo apt install moreutils  # Ubuntu/Debian"
  echo "            or: brew install moreutils      # macOS" 
  echo "            or: sudo pacman -S moreutils    # Arch Linux"
  echo ""
fi
'''
