---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app autobrr
  namespace: &namespace media
spec:
  # TODO: Remove suspend when VPN configuration is properly set up for torrent client
  suspend: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: volsync
      namespace: volsync-system
  interval: 1h
  path: ./kubernetes/apps/media/autobrr/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_SCHEDULE: "15 */8 * * *"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
