# TODO: Re-enable this ScaledObject when zigbee-controller hardware is back online
# Also uncomment the ./scaledobject.yaml line in kustomization.yaml
# and enable the zigbee-controller.internal probe in blackbox-exporter
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: zigbee2mqtt-scaler
spec:
  cooldownPeriod: 0
  minReplicaCount: 0
  maxReplicaCount: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zigbee2mqtt
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.observability.svc.cluster.local:9090
        query: probe_success{instance=~"zigbee-controller.+"}
        threshold: "1"
        ignoreNullValues: "0"
