---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "${APP}-restic-secret"
    destinationPVC: "${APP}"
    copyMethod: Direct