name: Feature Request
description: Suggest new functionality or improvements for the homelab
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea to improve the homelab? Let's discuss it!

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of enhancement is this?
      options:
        - New Application
        - Infrastructure Improvement
        - Automation/Task Enhancement
        - Monitoring/Observability
        - Security Enhancement
        - Storage/Backup
        - Networking
        - Documentation
        - Developer Experience
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see added or improved?
      placeholder: |
        Clear description of the proposed feature or improvement
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why This Would Be Useful
      description: What problem does this solve or what value does it add?
      placeholder: |
        - What pain point does this address?
        - How would this improve the homelab?
        - Who would benefit from this?

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Any thoughts on how this could be implemented?
      placeholder: |
        - Specific tools or technologies to consider
        - Configuration changes needed
        - Integration points with existing infrastructure

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about?
      placeholder: |
        - Other tools or methods considered
        - Why the proposed approach is preferred

  - type: checkboxes
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this would be?
      options:
        - label: Simple (configuration change or single app deployment)
        - label: Moderate (multiple components or infrastructure changes)
        - label: Complex (major architectural changes)

  - type: checkboxes
    id: priority
    attributes:
      label: Priority Level
      description: How important is this to you?
      options:
        - label: Nice to have
        - label: Would improve daily workflow
        - label: Addresses significant pain point
