---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: devices
spec:
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - unifi.hypyr.space
        - barbary.hypyr.space
        # - ups.internal  # TODO: configure UPS monitoring
        - kvm01.hypyr.space
        - kvm02.hypyr.space
        # - zigbee-controller.internal  # TODO: configure Zigbee controller monitoring
