---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://onepassword.external-secrets.svc.cluster.local
      vaults:
        5xbjxjzzgjq75rozxy44jvaooi: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-secret
            key: token
            namespace: external-secrets
