---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blackbox-exporter
spec:
  groups:
    - name: blackbox-exporter.rules
      rules:
        - alert: BlackboxInstanceDown
          expr: |
            probe_success == 0
          for: 5m
          annotations:
            summary: >-
              The host {{ $labels.instance }} is down
            runbook_url: "https://github.com/cpritchett/home-ops/blob/main/docs/CLUSTER-TROUBLESHOOTING.md#network-connectivity"
            description: >-
              Host is not responding to blackbox probes. Check network connectivity and host status. Use `ping {{ $labels.instance }}` and `nmap -p {{ $labels.port }} {{ $labels.instance }}` to troubleshoot.
          labels:
            severity: critical
