---
# TODO: Explore DNS over HTTPS (DoH) options for enhanced privacy:
#   - Cloudflare DoH: https://1.1.1.1:443/dns-query (already used in cert-manager)
#   - NextDNS DoH: https://dns.nextdns.io/{config-id} (privacy-focused with filtering)
#   - Quad9 DoH: https://dns.quad9.net:443/dns-query (security-focused)
#   - Need to verify Gatus DoH support and optimal configuration
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: flux-webhook
    url: https://flux-webhook.hypyr.space
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"

  - name: internet-connectivity
    url: https://1.1.1.1
    interval: 5m
    client:
      timeout: 10s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
        enabled: true
        failure-threshold: 2
        success-threshold: 1
        send-on-resolved: true
        webhook:
          url: "https://hc-ping.com/85f9d328-9c9c-4d44-8266-5638aa88ce1a"
          method: GET

metrics: true

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/cpritchett
  link: https://github.com/cpritchett
  buttons:
    - name: Github
      link: https://github.com/cpritchett
    - name: Homelab
      link: https://github.com/cpritchett/home-ops

web:
  port: ${GATUS_WEB_PORT}
