---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app maintainerr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      maintainerr:
        containers:
          app:
            image:
              repository: ghcr.io/jorenn92/maintainerr
              tag: 2.19.0@sha256:bee84707edaf589cda3d18b6813cbfe3a137b52786210c3a28190e10910c1240 # trunk-ignore(checkov/CKV_SECRET_6): legitimate container image SHA
            env:
              TZ: America/Chicago
              UI_PORT: &port 80
              BASE_PATH: "/"
            resources:
              requests:
                cpu: 10m
              limits:
                cpu: 100m  # Prevent runaway CPU usage
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ALL] }
    defaultPodOptions:
      hostUsers: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [1702]
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /opt/data
      tmpfs:
        type: emptyDir
        advancedMounts:
          maintainerr:
            app:
              - path: /opt/data/logs
                subPath: logs
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.hypyr.space"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
    service:
      app:
        ports:
          http:
            port: *port
