---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./rbac.yaml
configMapGenerator:
  - name: cloudflared-scripts
    files:
      - generate-config.sh=./init-container/generate-config.sh
generatorOptions:
  disableNameSuffixHash: true
