---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kromgo
  annotations:
    # Tunnel-only access: Exclude from external-dns to force tunnel routing
    # This prevents external-dns from creating public DNS records that bypass tunnel
    external-dns.alpha.kubernetes.io/exclude: "true"
    # tunnel.cloudflare.io/exclude: "false" # Default - include in tunnel
spec:
  hostnames:
    - kromgo.hypyr.space
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: kromgo
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /