---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-config
data:
  snmp.yml: |
    # Standard MIB-II modules for network interfaces
    modules:
      if_mib:
        walk:
          - 1.3.6.1.2.1.2.2.1.1     # ifIndex
          - 1.3.6.1.2.1.2.2.1.2     # ifDescr
          - 1.3.6.1.2.1.2.2.1.3     # ifType
          - 1.3.6.1.2.1.2.2.1.5     # ifSpeed
          - 1.3.6.1.2.1.2.2.1.8     # ifOperStatus
          - 1.3.6.1.2.1.2.2.1.10    # ifInOctets
          - 1.3.6.1.2.1.2.2.1.16    # ifOutOctets
          - 1.3.6.1.2.1.31.1.1.1.6  # ifHCInOctets
          - 1.3.6.1.2.1.31.1.1.1.10 # ifHCOutOctets
        lookups:
          - source_indexes: [ifIndex]
            lookup: ifDescr
        overrides:
          ifType:
            type: EnumAsInfo
      
      # Synology DSM module
      synology:
        walk:
          - 1.3.6.1.2.1.1           # System
          - 1.3.6.1.2.1.25.1        # Host Resources System
          - 1.3.6.1.2.1.25.2        # Host Resources Storage
          - 1.3.6.1.2.1.25.3        # Host Resources Device
          - 1.3.6.1.4.1.6574.1      # Synology System
          - 1.3.6.1.4.1.6574.2      # Synology Disk
          - 1.3.6.1.4.1.6574.3      # Synology RAID
          - 1.3.6.1.4.1.6574.4      # Synology UPS
          - 1.3.6.1.4.1.6574.101    # Synology Services
        lookups:
          - source_indexes: [diskIndex]
            lookup: diskID
          - source_indexes: [raidIndex]
            lookup: raidName
          - source_indexes: [serviceIndex]
            lookup: serviceName
      
      # UniFi module
      unifi:
        walk:
          - 1.3.6.1.2.1.1           # System
          - 1.3.6.1.2.1.2           # Interfaces
          - 1.3.6.1.4.1.41112.1.6   # UniFi Wireless
        lookups:
          - source_indexes: [ifIndex]
            lookup: ifDescr