# trunk-ignore(checkov/CKV2_GHA_1): GitHub Actions workflow requires write permissions for automation
---
name: Label Sync

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".github/labels.yaml"]
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

jobs:
  sync:
    name: Label Sync
    runs-on: ubuntu-24.04
    permissions: # trunk-ignore(checkov/CKV2_GHA_1): workflow requires write permissions
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: .github/labels.yaml

      - name: Sync Labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          config-file: .github/labels.yaml
          delete-other-labels: true
