---
name: Trunk Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  trunk-check:
    name: Trunk Check Runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          # Use appropriate check mode based on event type
          check-mode: >-
            ${{
              github.event_name == 'push' && 'push' ||
              (github.event_name == 'push' && 'push') ||
              (github.event_name == 'merge_group' && 'trunk_merge') ||
              'pull_request'
            }}

          # Set arguments for trunk check
          arguments: --monitor=false --ci
