name: Trunk Code Quality
on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  pull-requests: write 
  issues: write
  checks: write
  
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@v1
        with:
          post-annotations: true
